horapartida = (input('infome o horario quando sairam 0-23 '))
minutopartida = (input('informe os minutos da partida 0-59'))

horachegada = (input('Digite a hora de Chegada '))
minutochegada = (input('infrome o horario quando chegaram ao destino(horas e minutos): '))

descanso = int(input('informe quantos segundos ficaram parados para descansar:'))

Combustivel = float(input('quantos Litros de Combustível gastaram'))
preço_combustivel = (input('Preço da Gasosa'))

Distância = float(input('Quantos Km de viagem: '))

#converter o tempo para minuto 



